name: workflow

on:
  workflow_dispatch:

jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo bar
      - run: cat file
      - run: cat .github/workflows/workflow.yaml
